version: '3.7'

services:
  web:
    build: .
    command: ["pipenv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
volumes:
  downloads:
